spring:
  application:
    name: zuul-demo
server:
  port: 2103

zuul:
  routes:
    spring-boot-web: /springbootweb/**
  retryable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  connectTimeout: 500
  readTimeout: 5000
  maxAutoRetries: 1
  maxAutoRetriesNextServer: 3
  okToRetryOnAllOperations: true
  retryableStatusCodes: 500,404,502

eureka:
  client:
    serviceUrl:
      defaultZone: http://caizhijian:123456@localhost:8761/eureka/,http://caizhijian:123456@localhost:8762/eureka/