server:
  port: 8083
  servlet:
    context-path: /springbootweb

spring:
  application:
    name: spring-boot-web
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  cloud:
    client:
      ip-address: 127.0.0.1

  boot:
    admin:
      client:
        url: http://localhost:9091



eureka:
  client:
    serviceUrl:
      #defaultZone: http://caizhijian:123456@localhost:8761/eureka/,http://caizhijian:123456@localhost:8762/eureka/
      defaultZone: http://caizhijian:123456@localhost:8761/eureka/


  # 采用IP注册
  instance:
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:${server.servlet.context-path}
    metadata-map:
      management:
        context-path: /${server.servlet.context-path}
    health-check-url: http://localhost:${server.port}/${server.servlet.context-path}/actuator/health
    status-page-url: http://localhost:${server.port}${server.servlet.context-path}/actuator/info
    home-page-url: http://localhost:${server.port}/${server.servlet.context-path}/
    # 默认 30 秒
    lease-renewal-interval-in-seconds: 5
    # 默认 90 秒
    lease-expiration-duration-in-seconds: 5

management:
  endpoint:
    health:
      show-details: ALWAYS
  # 可以关闭制定的端点
  shutdown:
    enabled: false

  endpoints:
    web:
      base-path: /actuator #默认路径
      exposure:
        #include: ["configprops", "env", "health", "info", "threaddump", "logfile", "jhi-metrics", "prometheus" ]
        include: "*"


