spring:
  application:
  name: spring-boot-web
  servlet:
  multipart:
  max-file-size: 30MB
  max-request-size: 30MB

server:
    port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/


  # 采用IP注册
  instance:
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring:application:name}:${spring:cloud:client:ip-address}:${server:port}

management:
  endpoint:
    health:
      show-details: ALWAYS

  endpoints:
    web:
      exposure:
        include: configprops,beans