spring:
  application:
    name: eureka-client-article-service
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  cloud:
    client:
      ip-address: 127.0.0.1
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://caizhijian:123456@localhost:8761/eureka/

  # 采用IP注册
  instance:
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring:application:name}:${spring:cloud:client:ip-address}:${server:port}

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: ["configprops", "env", "health", "info", "threaddump", "logfile", "jhi-metrics", "prometheus" ]