server:
  port: 8084
  servlet:
    context-path: /task

spring:
  application:
    name: spring-boot-task
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  kafka:
    producer:
      #kafka服务地址和端口
      bootstrap-servers: 192.168.1.155:9092
      consumer:
        enable-auto-commit: true
        group-id: demo #群组ID
    consumer:
      bootstrap-servers: 192.168.1.155:9092
      group-id: test
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer