spring:
  application:
    name: practice-gateway-apollo
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  cloud:
    client:
      ip-address: 127.0.0.1
    gateway:
      routes:
        - id: spring-boot-web1
          uri: lb://spring-boot-web #目标地址
          predicates:
          - Path=/springbootweb/testway/** #路由规则
          filters:
            - RedirectTo=302, http://baidu.com #重定向操作

        - id: spring-boot-web2
          uri: lb://spring-boot-web #目标地址
          predicates:
            - Path=/springbootweb/testHystrix/** #路由规则
          filters:
            - name: Hystrix #熔断限流测试
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

        - id: spring-boot-web3
          uri: lb://spring-boot-web #目标地址
          predicates:
            - Path=/springbootweb/retry/** #路由规则
          filters:
            - name: Retry #重试过滤器
              args:
                retries: 3 #重试次数
                series: SERVER_ERROR #状态码配置（分段），符合某段状态码才会进行重试逻辑，默认值是 SERVER_ERROR，值是 5，也就是 5XX（5 开头的状态码），共有 5 个值

        - id: spring-boot-web4
          uri: lb://spring-boot-web #目标地址
          predicates:
            - Path=/springbootweb/** #路由规则
          filters:
            - name: CheckAuth2 #自定义过滤器
              args:
                name: 张三

#            - AddRequestHeader=X-Request-Foo, Bar #添加请求头
#      discovery:
#        locator:
#          lowerCaseServiceId: true

server:
  port: 2001

eureka:
  client:
    serviceUrl:
      defaultZone: http://caizhijian:123456@localhost:8761/eureka/,http://caizhijian:123456@localhost:8762/eureka/
    # 采用IP注册
  instance:
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 默认 30 秒
    lease-renewal-interval-in-seconds: 5
    # 默认 90 秒
    lease-expiration-duration-in-seconds: 5

#apoll配置
app:
  id: apollo-practice
apollo:
  meta: http://192.168.1.102:8080
  bootstrap:
    enabled: true

#测试apollo功能
testapollo1: 20200419
testapollo2:
  testapollo2_1: 1410
  testapollo2_2: 0000