spring:
  application:
    name: practice-gateway
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  cloud:
    client:
      ip-address: 127.0.0.1
    gateway:
      routes:
        - id: spring-boot-web
          uri: lb://spring-boot-web #目标地址
          predicates:
          - Path=/springbootweb/** #路由规则
#      discovery:
#        locator:
#          lowerCaseServiceId: true

server:
  port: 2001

eureka:
  client:
    serviceUrl:
      defaultZone: http://caizhijian:123456@localhost:8761/eureka/,http://caizhijian:123456@localhost:8762/eureka/
    # 采用IP注册
  instance:
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 默认 30 秒
    lease-renewal-interval-in-seconds: 5
    # 默认 90 秒
    lease-expiration-duration-in-seconds: 5